#!/usr/bin/perl

use strict;

my @x = ();
my @y = ();
my @min = ();
my @max = ();
my @text = ();

while (<>) {
	s/<b>//g;
	s/<\/b>//g;

	if (/<text top="([0-9]+)" left="([0-9]+)" width="([0-9]+)" height="([0-9]+)" font="[^"]*">(.*)<\/text>/) {
		my $x = $2 + $3 / 2;
		my $y = $1 + $4 / 2;
		my $text = $5;

		push @x, $x;
		push @y, $y;
		push @min, $2;
		push @max, $2 + $3;
		push @text, $text;
	}

	if (/<\/page/) {
		my $i;
		for ($i = 0; $i <= $#text; $i++) {
			if ($text[$i] =~ /Groups *Printed(.*)/) {
				my $group = $1;
				print "$ARGV\n";
				print "$group\n";
				$i++;

				my @streets = ();
				my @directions = ();
				my @directionx = ();
				my $direction = 0;
				for (; $i <= $#text; $i++) {
					if ($text[$i] =~ /bound$/i || $text[$i] =~ /\([NSEW]B\)$/ || $text[$i] =~ /^From/i || $text[$i] =~ /Leg$/i) {
						$directions[$direction] = $text[$i];
						$directionx[$direction] = $x[$i];
						$direction++;
					} elsif ($text[$i] =~ /Start/) {
						last;
					} else {
						if ($streets[$direction] eq "") {
							$streets[$direction] = $text[$i]
						} else {
							$streets[$direction] .= " $text[$i]";
						}
					}
				}

				for (my $x = 0; $x <= $#streets; $x++) {
					# print "$directions[$x]: $streets[$x]\n";
				}

				if ($text[$i] =~ /Start/) {
					$i++;
				}
				if ($text[$i] =~ /Time/) {
					$i++;
				}

				my @cols = ();
				my @colmin = ();
				my @colmax = ();
				for (; $i <= $#text; $i++) {
					last if $text[$i] =~ /\d:\d\d/;

					if ($#colmin >= 0 &&
					    ! ($min[$i] > $colmax[$#colmax] || $max[$i] < $colmin[$#colmin])) {
						$cols[$#cols] .= $text[$i];
						if ($min[$i] < $colmin[$#colmin]) {
							$colmin[$#colmin] = $min[$i];
						}
						if ($max[$i] > $colmax[$#colmax]) {
							$colmax[$#colmax] = $max[$i];
						}
					} else {
						push @cols, $text[$i];
						push @colmin, $min[$i];
						push @colmax, $max[$i];
					}
				}

				my @coldir = ();
				for (my $x = 0; $x <= $#cols; $x++) {
					my $mid = ($colmin[$x] + $colmax[$x]) / 2;
					my $best = -1;
					my $bestdist = 999999;
					for (my $y = 0; $y <= $#directions; $y++) {
						my $d = abs($mid - $directionx[$y]);
						if ($d < $bestdist) {
							$best = $y;
							$bestdist = $d;
						}
					}

					$coldir[$x] = $best;
				}
				for (my $x = 0; $x <= $#cols; $x++) {
					print "$directions[$coldir[$x]]: $cols[$x]: $colmin[$x] to $colmax[$x]\n";
				}

				print "\n";
			}
		}

		@x = ();
		@y = ();
		@min = ();
		@max = ();
		@text = ();
	}
}
