#!/usr/bin/perl

sub out {
	if ($walk1 != 0 && $walk2 != 0 && $walk3 != 0 && $walk4 != 0) {
		print @lines;
	} elsif (0) {
		for $line (@lines) {
			print "# $line";
		}
	}
}

while (<>) {
	($id, $name, $id2, $date, $time, @fields) = split(/,/);

	$key = "$id,$name,$id2,$date";
	if ($key ne $okey) {
		out();
		$walk1 = $walk2 = $walk3 = $walk4 = 0;
		@lines = ();
	}

	$walk1 += $fields[12];
	$walk2 += $fields[13];
	$walk3 += $fields[14];
	$walk4 += $fields[15];
	push @lines, $_;
	$okey = $key;
}

out();
