#!/usr/bin/perl

open(IN, "portland-intersections");
while (<IN>) {
	chomp;
	($name, $lat, $lon) = split(/,/);

	$name =~ s/BROADWAY ST/BROADWAY/g;
	$name =~ s/M L KING/MARTIN LUTHER KING/g;
	$name =~ s/MARTIN LUTHER KING JR\.?/MARTIN LUTHER KING/g;
	$name =~ s/\bPKY\b/PKWY/g;
	$lat{$name} = $lat;
	$lon{$name} = $lon;
}
close(IN);

while (<>) {
	chomp;
	@orig = split(/,/);

	$name = $orig[1];
	$name =~ s/ -- / \/ /g;
	$name =~ s/ & / \/ /g;
	$name =~ tr/a-z/A-Z/;
	$name =~ s/\bBLV\b/BLVD/g;
	$name =~ s/\bBV\b/BLVD/g;
	$name =~ s/\bPKY\b/PKWY/g;
	$name =~ s/BROADWAY ST/BROADWAY/g;
	$name =~ s/LOVE JOY/LOVEJOY/g;
	$name =~ s/M L KING/MARTIN LUTHER KING/g;
	$name =~ s/MLK/MARTIN LUTHER KING/g;
	$name =~ s/CESAR (E )?CHAVEZ BLVD/39TH AVE/g; # TIGER still has the old name
	$name =~ s/GLSIAN/GLISAN/g;
	$name =~ s/MARTIN LUTHER KING JR\.?/MARTIN LUTHER KING/g;

	@names = split(/ *\/ */, $name);

	for ($i = 0; $i <= $#names; $i++) {
		$ii = ($i + 1) % ($#names + 1);
		$code = "$names[$i] at $names[$ii]";

		if ($lat{$code} ne "") {
			$orig[5 + 12 + 8] = $lat{$code};
			$orig[5 + 12 + 8 + 1] = $lon{$code};
			last;
		}
	}

	print "$orig[0]";
	for ($i = 1; $i <= $#orig; $i++) {
		print ",$orig[$i]";
	}

	print "\n";
}
