#!/usr/bin/perl

for $file (<*.html>, <html/*.html>) {
	open(IN, "$file");
	while (<IN>) {
		if (/href="([^"]*pdf)">([^<]*)<\/a/) {
			print "$2 $1\n";
			next if -f "$2";

			$name = $2;
			$url = $1;

			unless ($url =~ /http:/) {
				$url = "http://www.portlandmaps.com$url";
			}

			system "curl -o '$name' '$url'";
		}
	}
}
